### PR TITLE
make adapter work cross-os, fix errors, add/update testing

### LINKED ISSUE #2: Filepath handling incomptible with Linux!
I tested the adapter on my installation and go the following result:

ls -la

```
drwxrwxrwx  2 root  root   4096 Aug 23 00:10 \Anwesenheit
-rw-rw-rw-  1 root  root   1602 Aug 23 00:06 \Anwesenheit\CCUioDaten.js
-rw-rw-rw-  1 root  root    700 Aug 23 00:06 \Anwesenheit\Geofency-Cloud-Mapper.js
-rw-rw-rw-  1 root  root   3609 Aug 23 00:06 \Anwesenheit\Monitor-Handy-Changes.js
drwxrwxrwx  2 root  root   4096 Aug 23 00:10 \Anzeigen
-rw-rw-rw-  1 root  root  10363 Aug 23 00:06 \Anzeigen\EG-LED-Anzeige.js
-rw-rw-rw-  1 root  root   8862 Aug 23 00:06 \Anzeigen\Status-Zaehler.js
-rw-rw-rw-  1 root  root   2065 Aug 23 00:06 \Anzeigen\SurveillanceStation-URLs.js
-rw-rw-rw-  1 root  root   5589 Aug 23 00:06 \Anzeigen\Vis-View-Steuerung.js
-rw-rw-rw-  1 root  root   1665 Aug 23 00:06 \Anzeigen\Vis-View-Wechseln.js
drwxrwxrwx  2 root  root   4096 Aug 23 00:10 \Arduino
-rw-rw-rw-  1 root  root   9827 Aug 23 00:06 \Arduino\Daten.js
```
The whole handling seems to be focussed on WIndows for now.

BTW: With nodejs (as I also learned some time ago) the preferred way to build path's is e.g. https://nodejs.org/api/path.html#path_path_join_paths ... So maybe use "split('.') and use this array to build the platform independent path for the files?!

### PR DESCRIPTION
**Pull request by Apollon77**
Hi Soef,

I needed to change more then I initially wanted (and also that's why several commits, simply sqash them :-) , but here is the changelog:
- update testing files and testing
- add adapter specific testing (initial script-to-file, check file-creation, changing files and check object update, add file and check object), both Travis-CI (https://travis-ci.org/Apollon77/iobroker.js2fs/builds/267886733) and Appveyor (https://ci.appveyor.com/project/Apollon77/iobroker-js2fs) are green for Linux, MacOS and Windows now!
- update code to not only work with windows paths (fixes #2)
- replace fs.watch by chokidar library to allow recursive watch also on Linux/Mac (not working with fs.watch)

I hope I have not damaged anything, especially with debugging because I have not tested this (but also not really touched it). There were still some things in it where I still do not really understand what/why you do several things ... but testings show that it works for the normal cases.

What you think?

Ingo F

### CODE REVIEW

**Comment by Apollon77** [comment]
Appveyor is currently broken somehow because of network issues ...  the errors there are not code related

**Comment by Apollon77** [comment]
if those are too many single commits i can also try a rebase ...

**Comment by soef** [comment]
I think most of your changes are very good. I don't check the testing functions. During your work I also changed a lot. After merging your pull request I will replace some of your changes.

**Comment by Apollon77** [comment]
should I send the second PR to add "sync" code from me so that you can rework everything together?!

**Pull request merged**
